version: "3.6"

x-common-variables: &common-variables
  MYSQL_USER: user
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: test
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    restart: unless-stopped
    
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./backend
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 9000:9000
    volumes:
      - ./backend:/app
    links:
      - mysql-db
    command: npm start
  client:
    build: .
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    links:
      - server
    command: npm start