export const todoActionsConstants = {

    "GET_TODOS_REQUEST" : "GET_TODOS_REQUEST",
    "GET_TODOS_SUCCESS" : "GET_TODOS_SUCCESS",
    "GET_TODOS_FAILURE" : "GET_TODOS_FAILURE",

    "GET_TODO_REQUEST" : "GET_TODO_REQUEST",
    "GET_TODO_SUCCESS" : "GET_TODO_SUCCESS",
    "GET_TODO_FAILURE" : "GET_TODO_FAILURE",

    "ADD_TODO_REQUEST" : "ADD_TODO_REQUEST",
    "ADD_TODO_SUCCESS" : "ADD_TODO_SUCCESS",
    "ADD_TODO_FAILURE" : "ADD_TODO_FAILURE",

    "UPDATE_TODO_REQUEST" : "UPDATE_TODO_REQUEST",
    "UPDATE_TODO_SUCCESS" : "UPDATE_TODO_SUCCESS",
    "UPDATE_TODO_FAILURE" : "UPDATE_TODO_FAILURE",
    
    "DELETE_TODO_REQUEST" : "DELETE_TODO_REQUEST",
    "DELETE_TODO_SUCCESS" : "DELETE_TODO_SUCCESS",
    "DELETE_TODO_FAILURE" : "DELETE_TODO_FAILURE",

    "UPDATE_STATUS_REQUEST" : "UPDATE_STATUS_REQUEST",
    "UPDATE_STATUS_SUCCESS" : "UPDATE_STATUS_SUCCESS",
    "UPDATE_STATUS_FAILURE" : "UPDATE_STATUS_FAILURE",
}